#! /bin/bash

# This file is a slight modification of python.AppImage/usr/bin/python3.12
# 1. Fixed an issue related to how 'self' is calculated (make it not care about whether its a link)
# 2. Added LD_LIBRARY_PATH

# If running from an extracted image, then export ARGV0 and APPDIR
if [ -z "${APPIMAGE}" ]; then
    export ARGV0="$0"

    self=$(realpath -s "${BASH_SOURCE[0]}") # Protect spaces (issue 55)
    export APPDIR=$(dirname "${self}")
fi

# Resolve the calling command (preserving symbolic links).
export APPIMAGE_COMMAND=$(command -v -- "$ARGV0")

# Export TCl/Tk
export TCL_LIBRARY="${APPDIR}/usr/share/tcltk/tcl8.6"
export TK_LIBRARY="${APPDIR}/usr/share/tcltk/tk8.6"
export TKPATH="${TK_LIBRARY}"

# Export SSL certificate
export SSL_CERT_FILE="${APPDIR}/opt/_internal/certs.pem"

# Call Python

export LD_LIBRARY_PATH=${APPDIR}/usr/lib:${LD_LIBRARY_PATH}
"$APPDIR/opt/python3.12/bin/python3.12" -I -m minigalaxy "$@"

