name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper dh-python python3-all python3-setuptools help2man devscripts gettext lsb-release xmlstarlet git build-essential
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Prepare release files
      id: tag
      run: |
        ./scripts/credit-weblate-translators.sh
        ./scripts/create-release.sh
      env:
        DEBFULLNAME: ${{ secrets.DEBFULLNAME }}
        DEBEMAIL: ${{ secrets.DEBEMAIL }}
    - name: Build deb package
      run: |
        dpkg-buildpackage -us -uc
    - name: Commit changes
      run: |
        git config --global user.name 'Wouter Wijsman'
        git config --global user.email 'sharkwouter@users.noreply.github.com'
        git add pyproject.toml data/io.github.sharkwouter.Minigalaxy.metainfo.xml debian/changelog minigalaxy/version.py
        git add README.md data/ui/about.ui
        git commit -m "Add new release"
        git push
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.VERSION }}
        name: Minigalaxy version ${{ steps.tag.outputs.VERSION }}
        body_path: release.md
        prerelease: true
        files: |
          ../minigalaxy_*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
