name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-26.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper dh-python python3-all help2man devscripts gettext lsb-release xmlstarlet git build-essential pybuild-plugin-pyproject
        pip install setuptools python-appimage build
    - uses: actions/checkout@v6
      with:
        ref: master
    - name: Prepare release files
      id: tag
      run: |
        ./scripts/credit-weblate-translators.sh
        ./scripts/create-release.sh
      env:
        DEBFULLNAME: ${{ secrets.DEBFULLNAME }}
        DEBEMAIL: ${{ secrets.DEBEMAIL }}
    - name: Build deb package
      run: |
        dpkg-buildpackage -us -uc
    - name: Build AppImage
      uses: kohlerdominik/docker-run-action@v2.1.0
      with:
        image: quay.io/pypa/manylinux_2_28_x86_64
        volumes: ${{ github.workspace }}:/mnt/minigalaxy
        run: |
          /mnt/minigalaxy/scripts/make-appimage.sh
    - name: Commit changes
      run: |
        git config --global user.name 'Wouter Wijsman'
        git config --global user.email 'sharkwouter@users.noreply.github.com'
        git add pyproject.toml data/io.github.sharkwouter.Minigalaxy.metainfo.xml debian/changelog minigalaxy/version.py
        git add README.md minigalaxy/ui/data/about.ui
        git commit -m "Add new release"
        git push
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ steps.tag.outputs.VERSION }}
        name: Minigalaxy version ${{ steps.tag.outputs.VERSION }}
        body_path: release.md
        prerelease: true
        # the appimage script also builds the wheel, both are placed in the same directory
        files: |
          ../minigalaxy_*.deb
          ./build-appimage/output/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
